### PR TITLE
refactor: Remove unnecessary try-catch block

### LINKED ISSUE #14: Remove unnecessary try/catch clause
Issue is [here](https://github.com/asyncapi/extensions-catalog/blob/master/test/test.js#L15-L39). Just remove the try/catch as it is not needed. Exactly the same issue was solved [here](https://github.com/asyncapi/asyncapi/pull/441)﻿

### PR DESCRIPTION
**Pull request by philrussel21**
refactor: remove unnecessary try-catch block in the test file.

ISSUE: 
Remove unnecessary try/catch clause
Resolves #14

### CODE REVIEW

**Comment by derberg** [comment]
@philrussel21 Thanks so much for the contribution. Enjoy the Haktoberfest.

**Comment by derberg** [comment]
@philrussel21 we have more issues in case you are interested -> https://www.asyncapi.com/blog/hacktoberfest-2020

**Comment by philrussel21** [comment]
You're very welcome. Happy to help out! Having a look on your HacktoberFest GoogleSheet Issues 👍

**Comment by derberg** [comment]
@philrussel21 would you mind sharing with me how did you find out about AsyncAPI and this issue? we made some effort into Hacktoberfest and want to identify what efforts were the best for contributors and how they learned about us, so next Hacktoberfest is even better

**Comment by philrussel21** [comment]
Hi @derberg ! I appreciate the effort being put into improving the next Hacktoberfest. 

I remember following a link posted in the Hacktoberfest Discord channel which took me to a more advance Issue. There was however a youtube link to a video which briefly explains the said issue and from youtube I found the Google Sheets link which I used as a reference to pick a more appropriate issue to my experience.

I hope my feedback helps!

**Comment by derberg** [comment]
@philrussel21 that helps a lot, thanks so much. So far looks like Google Sheets was a very good solution

**Pull request merged**
