### PR TITLE
chore(ci): change pages to markdown

### PR DESCRIPTION
**Pull request by Shurtu-gal**
See also https://github.com/asyncapi/website/pull/2938

### CODE REVIEW

**Review by derberg — APPROVED** [review]
this workflow also modifies "/config/edit-page-config.json" that is part of website. If nothing has changed there, all good

merge when you're ready

**Comment by Shurtu-gal** [comment]
There is no change in `/config/edit-page-config.js` though. Can be merged once the migration is merged.

**Comment by Shurtu-gal** [comment]
@akshatnema could you remove the `do-not-merge` label.

**Pull request merged**
